// <auto-generated />
namespace ShopOnline.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addDetailContact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDetailContact));
        
        string IMigrationMetadata.Id
        {
            get { return "202005021205066_addDetailContact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
